spring:
  batch:
    initialize-schema: never   # 1
  application:
    name: BATCH
#  datasource:
#    url: jdbc:mariadb://localhost:3306
#    driver-class-name: org.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  influx:
    url: http://localhost:8086
    org: my-org
    bucket: my-bucket
    token: my-token
    logLevel: BODY
    readTimeout: 5s
    writeTimeout: 10s
    connectTimeout: 5s
meraki:
  secret: ${MERAKI_SECRET}
  network_id: ${MERAKI_NETWORK_ID:localhost}