properties:
  meraki:
    secret: ${MERAKI_SECRET:asd}
    networks: ${MERAKI_NETWORK_ID:localhost}
    url: ${MERAKI_URL:https://api.meraki.com/api/v1}
spring:
  application:
    name: BATCH
  datasource:
    url: jdbc:mysql://localhost:3306/wifi6?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dltjgus119@@
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  influxdb:
    url: aimon.jnu.ac.kr:8086
    username: root
    password: dltjgus119@@
    database: test
    retention-policy: autogen
    connect-timeout: 5s
    read-timeout: 5s
    write-timeout: 10s
    gzip: true
#  influxdb:


  batch:
    jdbc:
      initialize-schema: always
